"""Periodic SEO audit across posts, pages, and tools (.github/workflows/seo_audit.yml
runs this monthly).

Auto-fixes (low-risk, bounded): missing or badly-sized SEO title/meta
description get regenerated by Claude from the existing content and
written straight back -- this doesn't touch the actual post content, just
the search-result snippet, so it's safe to do unattended.

Report-only (not auto-fixed, needs a human): thin content (a full rewrite
is too risky to do unattended) and outbound links on tool pages that no
longer resolve (the tool may have rebranded/moved/shut down -- worth a
human decision, not an automatic edit).

Usage: python3 automation/seo_audit.py [--dry-run] [--fix-meta]
"""

from __future__ import annotations

import argparse
import re

import anthropic
import requests

from config import Settings
from wp_client import WPClient

TITLE_MAX = 60
DESC_MIN = 50
DESC_MAX = 155
THIN_CONTENT_WORDS = 300

CONTENT_TYPES = [
    {"endpoint": "posts", "label": "post", "path_prefix": "blog"},
    {"endpoint": "pages", "label": "page", "path_prefix": None},
    {"endpoint": "tool", "label": "tool", "path_prefix": "tools"},
]


def word_count(html: str) -> int:
    text = re.sub(r"<[^>]+>", " ", html)
    return len(text.split())


def generate_meta(client: anthropic.Anthropic, settings: Settings, title: str, content_html: str) -> dict:
    text = re.sub(r"<[^>]+>", " ", content_html)[:3000]
    response = client.messages.create(
        model=settings.anthropic_model,
        max_tokens=300,
        system=(
            "You write SEO title tags and meta descriptions for a business-admin-tools "
            "directory site. Respond with ONLY a JSON object: "
            '{"seo_title": "...under 60 characters...", "meta_description": "...under 155 characters..."}'
        ),
        messages=[{"role": "user", "content": f"Page title: {title}\n\nContent:\n{text}"}],
    )
    import json

    raw = response.content[0].text.strip()
    raw = re.sub(r"^```(?:json)?\n?|\n?```$", "", raw)
    return json.loads(raw)


def check_outbound_link(url: str) -> bool:
    try:
        resp = requests.head(url, timeout=10, allow_redirects=True)
        if resp.status_code >= 400:
            resp = requests.get(url, timeout=10, allow_redirects=True)
        return resp.status_code < 400
    except requests.RequestException:
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fix-meta", action="store_true", default=True, help="Auto-fix missing/oversized SEO meta (default: on)")
    parser.add_argument("--no-fix-meta", dest="fix_meta", action="store_false")
    parser.add_argument("--check-links", action="store_true", help="Also HEAD-check every tool's outbound link (slow)")
    args = parser.parse_args()

    settings = Settings()
    settings.validate()
    wp = WPClient(settings)
    client = anthropic.Anthropic(api_key=settings.anthropic_api_key)

    meta_fixes = []
    thin_content = []
    broken_links = []

    for ct in CONTENT_TYPES:
        items = wp.list_all(ct["endpoint"], status="publish")
        for item in items:
            title = item["title"]["rendered"]
            content_html = item.get("content", {}).get("rendered", "")
            meta = item.get("meta", {}) or {}
            seo_title = meta.get("_yoast_wpseo_title", "")
            meta_desc = meta.get("_yoast_wpseo_metadesc", "")

            needs_title = not seo_title or len(seo_title) > TITLE_MAX
            needs_desc = not meta_desc or not (DESC_MIN <= len(meta_desc) <= DESC_MAX)

            if needs_title or needs_desc:
                if args.fix_meta:
                    fixed = generate_meta(client, settings, title, content_html)
                    body = {"meta": {}}
                    if needs_title:
                        body["meta"]["_yoast_wpseo_title"] = fixed["seo_title"]
                    if needs_desc:
                        body["meta"]["_yoast_wpseo_metadesc"] = fixed["meta_description"]
                    wp.update(ct["endpoint"], item["id"], body)
                    meta_fixes.append(f"{ct['label']} '{title}' (id {item['id']})")
                else:
                    meta_fixes.append(f"[NOT FIXED, --no-fix-meta] {ct['label']} '{title}' (id {item['id']})")

            if ct["label"] != "tool" and word_count(content_html) < THIN_CONTENT_WORDS:
                thin_content.append(f"{ct['label']} '{title}' (id {item['id']}, ~{word_count(content_html)} words)")

            if args.check_links and ct["label"] == "tool":
                outbound = (item.get("acf") or {}).get("outbound_url")
                if outbound and not check_outbound_link(outbound):
                    broken_links.append(f"tool '{title}' (id {item['id']}) -> {outbound}")

    print(f"\n=== SEO meta {'fixed' if args.fix_meta else 'flagged'}: {len(meta_fixes)} ===")
    for line in meta_fixes:
        print(f"  {line}")

    print(f"\n=== Thin content (needs human review): {len(thin_content)} ===")
    for line in thin_content:
        print(f"  {line}")

    if args.check_links:
        print(f"\n=== Broken outbound links (needs human review): {len(broken_links)} ===")
        for line in broken_links:
            print(f"  {line}")


if __name__ == "__main__":
    main()
